/**
 * Pre-computes the QR code embedded in every chart so the runtime needs no QR library.
 * Usage: npm run gen:qr [-- <url>]
 */
import { writeFileSync } from "node:fs";

import QRCode from "qrcode";

const url = process.argv[2] ?? "https://github.com/furkanmeclis/smith-charts-mcp";
const qr = QRCode.create(url, { errorCorrectionLevel: "M" });
const n = qr.modules.size;
const rows: string[] = [];
for (let y = 0; y < n; y++) {
  let row = "";
  for (let x = 0; x < n; x++) row += qr.modules.get(y, x) ? "1" : "0";
  rows.push(row);
}
const out = `// Generated by scripts/generate-qr.ts — do not edit by hand.
export const QR_URL = ${JSON.stringify(url)};
export const QR_ROWS: readonly string[] = ${JSON.stringify(rows, null, 2)};
`;
writeFileSync(new URL("../src/render/qr-data.ts", import.meta.url), out);
console.log(`QR v${qr.version} (${n}×${n}) for ${url}`);
